# Generated by Django 4.1.5 on 2023-01-09 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.FloatField()),
                ('current_position', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(null=True)),
            ],
        ),
    ]
